#!/usr/bin/env bash
# usage: findv regexp [targetpath]
# 第一引数に与えた正規表現で、第二引数内 (未指定の場合はカレントディレクトリ) のディレクトリ内のファイルの名前を再帰的に検索し、
# マッチしたファイルを候補として表示し、入力した番号のファイルパスを標準出力する

set -ue -o pipefail

function main(){
  matches="$(
    type fdfind > /dev/null 2>&1 \
      && fdfind "${2:-.}" --type f | grep -iP "${1}" \
      || find "${2:-.}" -type f | grep -iP "${1}" \
  )"
  echo "${matches}" | grep -iP --color=always "${1}" | nl 1>&2
  echo -n "input target file line number: " 1>&2
  read number 2> /dev/null
  if [ "${number}" = "" ]; then
    exit 1
  fi
  if [ $? = 0 ]; then
    echo "${matches}" | sed -n "${number}p"
    exit $?
  fi
  exit 1
}

main "${@}"
